version: '3.4'

services:
  flask:
    build: 
      context: ./web-services
      dockerfile: Dockerfile
    container_name: flask
    volumes:
      - ./web-services:/app
    environment:
      - FLASK_APP=/app/app.py
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      web-service:
        aliases:
          - docker-flask
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - web-service
    restart: always

networks:
  web-service:
