version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # links:
    #   - db
    volumes:
      - type: bind
        source: ./web-services
        target: //app

  # db:
  #   build: ./db