version: '3.2'

services:
  web:
    build:
      context: ./web-services
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # links:
    #   - db
    volumes:
      - ./web-services:/app
      # - type: bind
      #   source: ./web-services
      #   target: /app

  # db:
  #   build: ./db